# GoReleaser configuration for mkrel
# Docs: https://goreleaser.com
version: 2

project_name: mkrel

before:
  hooks:
    - go mod tidy

builds:
  - id: mkrel
    main: ./cmd/mkrel
    binary: mkrel
    # CGO_ENABLED=0 creates fully static binaries
    env:
      - CGO_ENABLED=0
    # Build for multiple OS/architectures
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    # Inject version info at build time using ldflags
    ldflags:
      - -s -w
      - -X github.com/kloudlabs-io/mkrel/internal/cli.Version={{.Version}}
      - -X github.com/kloudlabs-io/mkrel/internal/cli.Commit={{.Commit}}
      - -X github.com/kloudlabs-io/mkrel/internal/cli.Date={{.Date}}

archives:
  - id: default
    formats:
      - tar.gz
    # Use zip for Windows
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

# Disable changelog - using Release Drafter for release notes
changelog:
  disable: true

# Homebrew cask configuration (replaces deprecated brews)
homebrew_casks:
  - repository:
      owner: kloudlabs-io
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    commit_author:
      name: Sergei Kolobov
      email: sergei@kloudlabs.io
    homepage: "https://github.com/kloudlabs-io/mkrel"
    description: "Release management tool with Git Flow and CalVer/SemVer support"
    license: "MIT"

release:
  github:
    owner: kloudlabs-io
    name: mkrel
  draft: false
  prerelease: auto
